### ISSUE TITLE
handle 404 error code, received from /v1/kv/ endpoint

### ISSUE THREAD

**Issue by ruslansennov** [vert-x3/vertx-consul-client#37]
We need to process the 404 error code from `/v1/kv/` endpoint as a successful result, because this is a valid situation. As a result, an empty `KeyValue` or `KeyValueList` can returned.
Also see #36

**Comment by melihcelik** [comment]
We were experimenting with vert.x and vertx-consul-client, KeyPrefix watch to be precise, when we identified high loads on consul agent and further analysis on the issue pointed us to this change. Due to this change, client code at `WatchImpl.KeyPrefix` makes a blocking call to consul. This call immediately returns with an HTTP-404 response, rather than waiting for a certain amount of time. Since 404 is identified as a valid response, the watch implementation repeats the call immediately, rather than waiting for a certain period of time. Since the client is repeating the HTTP call over and over again, CPU load on consul agent increases dramatically. When multiple instances are running, consul agent can no longer cope with the load.
@ruslansennov , what would you suggest, shall we follow the approach you suggested on issue #36 or should this change be reverted so that an HTTP-404 would trigger the logic in `WatchImpl#fetch` method that gradually increases the wait time after failed requests?

**Comment by ruslansennov** [comment]
Hi. I'm offline till end of week, sorry. I'll take a look later.
